### PR TITLE
EZEE-1451: Simplify mime type configuration

### PR DESCRIPTION
**Pull request by webhdx**
**JIRA: https://jira.ez.no/browse/EZEE-1451**

**This PR is obsolete as there are some issues after we've changed repository name. I've created valid duplicate: #19**

Mime types are now put into groups with common content type:

```yaml
ez_systems_multi_file_upload:
    location_mappings:
        -   # gallery
            content_type_identifier: gallery
            mime_type_filter:
                - video/*
                - image/*
            mappings:
                -   # images
                    mime_types:
                        - image/jpeg
                        - image/jpg
                        - image/pjpeg
                        - image/pjpg
                        - image/png
                        - image/bmp
                        - image/gif
                        - image/tiff
                        - image/x-icon
                        - image/webp
                    content_type_identifier: image
                    content_field_identifier: image
                    name_field_identifier: name
                -   # videos
                    mime_types:
                        - video/avi
                        - video/mpeg
                        - video/quicktime
                        - video/mp4
                        - video/webm
                        - video/3gpp
                        - video/x-msvideo
                        - video/ogg
                    content_type_identifier: video
                    content_field_identifier: file
                    name_field_identifier: name
                -   # .svg files are not supported by Image content type atm
                    mime_types:
                        - image/svg+xml
                    content_type_identifier: file
                    content_field_identifier: file
                    name_field_identifier: name
        -   # folder
            content_type_identifier: folder
            mappings:
                -   # files
                    mime_types:
                        - application/msword
                        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                        - application/vnd.ms-excel
                        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                        - application/vnd.ms-powerpoint
                        - application/vnd.openxmlformats-officedocument.presentationml.presentation
                        - application/pdf
                    content_type_identifier: file
                    content_field_identifier: file
                    name_field_identifier: name

    default_mappings:
        -   # image
            mime_types:
                - image/jpeg
                - image/jpg
                - image/pjpeg
                - image/pjpg
                - image/png
                - image/bmp
                - image/gif
                - image/tiff
                - image/x-icon
                - image/webp
            content_type_identifier: image
            content_field_identifier: image
            name_field_identifier: name
        -   # file
            mime_types:
                - image/svg+xml
                - application/msword
                - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                - application/vnd.ms-excel
                - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                - application/vnd.ms-powerpoint
                - application/vnd.openxmlformats-officedocument.presentationml.presentation
                - application/pdf
            content_type_identifier: file
            content_field_identifier: file
            name_field_identifier: name

    fallback_content_type:
        content_type_identifier: file
        content_field_identifier: file
        name_field_identifier: name
```

# TODO
- [x] reflect changes on the frontend (@sunpietro)

### CODE REVIEW

**Comment by andrerom** [comment]
@lserwatka @webhdx Is this intended for the release?


Side, on platform-demo I'm getting _(seems Configuration.php is missing a sane default)_:
```
Notice: Undefined index: name_field_identifier in /Users/andrerom/Sites/www/ezplatform/vendor/ezsystems/ezplatform-multi-file-upload/bundle/ApplicationConfig/Providers/ContentTypeMappings.php on line 101

Notice: Undefined index: name_field_identifier in /Users/andrerom/Sites/www/ezplatform/vendor/ezsystems/ezplatform-multi-file-upload/bundle/ApplicationConfig/Providers/ContentTypeMappings.php on line 87
```

**Comment by webhdx** [comment]
@andrerom Yes we want that to be a part of `rc` release, frontend part needs to be updated to handle new configuration. I'm not sure about the ETA tho (ping @sunpietro). 

Mentioned issue will be resolved in this ticket: https://jira.ez.no/browse/EZP-27204

**Comment by sunpietro** [comment]
I'm on it

**Comment by sunpietro** [comment]
ping @micszo

**Comment by webhdx** [comment]
@sunpietro Where is the fix? I don't see it in this PR. I'm not sure if it will work for testing purposes because https://jira.ez.no/browse/EZP-27204 is not yet fixed.

**Comment by webhdx** [comment]
@sunpietro @micszo Solved. You should be able to test it without problems (ignore my previous message).

**Comment by micszo** [comment]
yes yes, I'm getting there ;)

**Comment by micszo** [comment]
ezplatform-ee and ezplatform-ee-demo OK.
Platform metas to go.

**Comment by webhdx** [comment]
@sunpietro My previous comment could be misleading. 

zrzut ekranu 2017-04-06 o 15 02 23

We still need to fix that. Please create separate issue for that. @micszo confirmed it can be reproduced on Platform.

**Comment by andrerom** [comment]
Needs rebase now, also @sunpietro maybe you can rather open PR against this branch to get @micszo to merge, or he needs to solve the permission issue so we can solve this before rc1 tomorrow.

**Comment by webhdx** [comment]
@andrerom @lserwatka It looks like this PR is broken due to repository name change. It cannot be automatically merged even though there are no conflicts if you look at the code. Any idea how can we fix that or we do manual merge on this one?

**Comment by webhdx** [comment]
Guys, just a heads up: I've created new PR: #19 because this one has issues after repository name change.

**Comment by lserwatka** [comment]
Closed in favour of #19

**Pull request closed without merging**
